import type { IconType } from "react-icons";
import {
  SiNextdotjs,
  SiReact,
  SiTypescript,
  SiJavascript,
  SiTailwindcss,
  SiNodedotjs,
  SiPython,
  SiGraphql,
  SiPostgresql,
  SiMongodb,
  SiRedis,
  SiPrisma,
  SiKotlin,
  SiOpenjdk,
  SiDocker,
  SiVercel,
  SiOpenai,
  SiAndroid,
  SiFramer,
  SiVuedotjs,
  SiVite,
  SiHtml5,
  SiCss,
  SiExpress,
  SiFastapi,
  SiGo,
  SiMysql,
  SiSupabase,
  SiFirebase,
  SiFlutter,
  SiSwift,
  SiApple,
  SiKubernetes,
  SiGithubactions,
  SiLinux,
  SiNginx,
  SiAnthropic,
  SiHuggingface,
  SiTensorflow,
  SiPytorch,
  SiGit,
  SiFigma,
  SiJest,
  SiNpm,
  SiWebpack,
  SiPostman,
  SiGithub,
  SiStripe,
  SiNetlify,
} from "react-icons/si";
import { TbApi, TbBrandReactNative, TbVectorBezier2, TbBroadcast } from "react-icons/tb";
import { LuBrain, LuWorkflow, LuCode } from "react-icons/lu";
import { VscVscode } from "react-icons/vsc";
import { FaAws, FaShopify } from "react-icons/fa6";

const iconMap: Record<string, IconType> = {
  "Next.js": SiNextdotjs,
  React: SiReact,
  TypeScript: SiTypescript,
  JavaScript: SiJavascript,
  Tailwind: SiTailwindcss,
  "Framer Motion": SiFramer,
  Vue: SiVuedotjs,
  Vite: SiVite,
  HTML5: SiHtml5,
  CSS3: SiCss,
  "Node.js": SiNodedotjs,
  Python: SiPython,
  Express: SiExpress,
  FastAPI: SiFastapi,
  REST: TbApi,
  GraphQL: SiGraphql,
  Microservices: LuWorkflow,
  Go: SiGo,
  PostgreSQL: SiPostgresql,
  MongoDB: SiMongodb,
  Redis: SiRedis,
  Prisma: SiPrisma,
  MySQL: SiMysql,
  Supabase: SiSupabase,
  Firebase: SiFirebase,
  Kotlin: SiKotlin,
  Java: SiOpenjdk,
  "React Native": TbBrandReactNative,
  "Android SDK": SiAndroid,
  Flutter: SiFlutter,
  Swift: SiSwift,
  iOS: SiApple,
  Docker: SiDocker,
  AWS: FaAws,
  Kubernetes: SiKubernetes,
  "CI/CD": LuWorkflow,
  Vercel: SiVercel,
  "GitHub Actions": SiGithubactions,
  Linux: SiLinux,
  Nginx: SiNginx,
  OpenAI: SiOpenai,
  Anthropic: SiAnthropic,
  RAG: LuBrain,
  LangChain: TbVectorBezier2,
  "Vector DB": TbVectorBezier2,
  "Hugging Face": SiHuggingface,
  TensorFlow: SiTensorflow,
  PyTorch: SiPytorch,
  Git: SiGit,
  Figma: SiFigma,
  Jest: SiJest,
  npm: SiNpm,
  Webpack: SiWebpack,
  Postman: SiPostman,
  "VS Code": VscVscode,
  GitHub: SiGithub,
  Stripe: SiStripe,
  Netlify: SiNetlify,
  "Tailwind CSS": SiTailwindcss,
  WebSockets: TbBroadcast,
  "Shopify Headless": FaShopify,
  "Shopify Plus": FaShopify,
  Liquid: FaShopify,
};

export function getSkillIcon(name: string): IconType {
  return iconMap[name] ?? LuCode;
}

export { LuBrain };
